const Profiles = [
    {
      id: "@Mari_Viaja",
      userName: "Maria",
      userLastName: "Garcia",
      email: "maria.garcia@gmail.com",
      birthday: "15/12/2005",
      country: "Colombia",
      city: "Bogotá",
      password: "#Mariita05",
    },
    {
      id: "@AnneMtz",
      userName: "Ana",
      userLastName: "Martinez",
      email: "aneemtza@gmail.com",
      birthday: "04/08/1997",
      country: "Perú",
      city: "Machu Picchu",
      password: "2024-AnnePeru",
    },
    {
      id: "@Sofi.Rojas23",
      userName: "Sofia",
      userLastName: "Rojas",
      email: "sofia_ro@gmail.com",
      birthday: "28/11/1981",
      country: "Colombia",
      city: "Cartagena",
      password: "sofIa123*",
    },
    {
      id: "@travelerIsa",
      userName: "Isabella",
      userLastName: "Perez",
      email: "bella2001@gmail.com",
      birthday: "17/02/2001",
      country: "Brasil",
      city: "Río de Janeiro",
      password: "Bella$C140",
    },
    {
      id: "@ValGonz4554",
      userName: "Valentina",
      userLastName: "Gonzalez",
      email: "vale-gonzalez@gmail.com",
      birthday: "09/09/1992",
      country: "México",
      city: "Ciudad de México",
      password: "@ValGonz45",
    },
    {
      id: "@NomadCami5820",
      userName: "Camila",
      userLastName: "Lopez",
      email: "cami.cami@gmail.com",
      birthday: "15/06/2003",
      country: "Chile",
      city: "Desierto de Atacama",
      password: "Cami/5820",
    },
    {
      id: "@Gabi_SoloTravs",
      userName: "Gabriela",
      userLastName: "Fernandez",
      email: "gaby.fernandez@gmail.com",
      birthday: "20/03/1995",
      country: "Costa Rica",
      city: "Pava",
      password: ".SoloTravs100",
    },
    {
      id: "@Luci1711",
      userName: "Lucia",
      userLastName: "Silva",
      email: "luci_sil@gmail.com",
      birthday: "01/12/1971",
      country: "Ecuador",
      city: "Islas Galápagos",
      password: "*Lucia17",
    },
    {
      id: "@Elena_Solitaria",
      userName: "Elena",
      userLastName: "Torres",
      email: "tototo20@gmail.com",
      birthday: "11/07/2004",
      country: "Bolivia",
      city: "Salar de Uyuni",
      password: "9876543210Ele#",
    },
    {
      id: "@CaroTravels",
      userName: "Carolina",
      userLastName: "Morales",
      email: "caro.morales@gmail.com",
      birthday: "05/09/1972",
      country: "Panamá",
      city: "Ciudad de Panamá",
      password: "/P4n4m4/",
    },
  ];
  
  console.log(Profiles);
  